# Generated by Django 2.1.7 on 2019-07-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content_info',
            name='link_form',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content_info',
            name='place',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content_info',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info_site',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='info_site',
            name='type_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_site', to='login.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
